// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMithila.SharedDataAccess.EFCore;

namespace SocialMithila.SharedDataAccess.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Comments", b =>
                {
                    b.Property<long>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<long?>("ParentCommentId")
                        .HasColumnType("bigint");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId")
                        .HasName("PK__Comments__C3B4DFCA7B055521");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "CreatedOn");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.ContentReports", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.HasKey("ReportId")
                        .HasName("PK__ContentR__D5BD4805ECBF10AE");

                    b.HasIndex("ReporterId");

                    b.ToTable("ContentReports");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.ConversationMembers", b =>
                {
                    b.Property<long>("ConversationMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("IsMuted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("JoinedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ConversationMemberId")
                        .HasName("PK__Conversa__6CF98427BE7F3769");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "UserId")
                        .HasName("IX_ConversationMembers_Conversation_User");

                    b.ToTable("ConversationMembers");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Conversations", b =>
                {
                    b.Property<long>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMessageOn")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("ConversationId")
                        .HasName("PK__Conversa__C050D877DB208581");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Friendships", b =>
                {
                    b.Property<long>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddresseeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("FriendshipId")
                        .HasName("PK__Friendsh__4D531A542EFD9126");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique()
                        .HasName("UX_Friendship_Requester_Addressee");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.GroupMembers", b =>
                {
                    b.Property<long>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("JoinedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GroupMemberId")
                        .HasName("PK__GroupMem__344812925772D5FA");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique()
                        .HasName("UX_GroupMembers_Group_User");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Groups", b =>
                {
                    b.Property<long>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("GroupId")
                        .HasName("PK__Groups__149AF36A1A68D5C9");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Hashtags", b =>
                {
                    b.Property<int>("HashtagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("HashtagId")
                        .HasName("PK__Hashtags__BEFA912A84475444");

                    b.HasIndex("Tag")
                        .IsUnique()
                        .HasName("UQ__Hashtags__C4516413AC41CE82")
                        .HasFilter("[Tag] IS NOT NULL");

                    b.ToTable("Hashtags");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.MediaFiles", b =>
                {
                    b.Property<long>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(260)")
                        .HasMaxLength(260);

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("MediaId")
                        .HasName("PK__MediaFil__B2C2B5CF68DED6AF");

                    b.HasIndex("OwnerUserId")
                        .HasName("IX_MediaFiles_Owner");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.MessageAttachments", b =>
                {
                    b.Property<long>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("AttachmentId")
                        .HasName("PK__MessageA__442C64BE77F1800F");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageAttachments");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.MessageReceipts", b =>
                {
                    b.Property<long>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("DeliveryStatus")
                        .HasColumnType("tinyint");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StatusOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReceiptId")
                        .HasName("PK__MessageR__CC08C4206288BD81");

                    b.HasIndex("UserId");

                    b.HasIndex("MessageId", "UserId")
                        .HasName("IX_MessageReceipts_Message_User");

                    b.ToTable("MessageReceipts");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Messages", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("EditedOn")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("MessageId")
                        .HasName("PK__Messages__C87C0C9CA01E0C1F");

                    b.HasIndex("SenderId");

                    b.HasIndex("ConversationId", "CreatedOn");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Notifications", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E1291BE5B8F");

                    b.HasIndex("ActorId");

                    b.HasIndex("UserId", "IsRead", "CreatedOn")
                        .HasName("IX_Notifications_User_IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.PostMedia", b =>
                {
                    b.Property<long>("PostMediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("PostMediaId");

                    b.HasIndex("PostId");

                    b.ToTable("PostMedia");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.PostTags", b =>
                {
                    b.Property<int>("PostTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HashtagId")
                        .HasColumnType("int");

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint");

                    b.HasKey("PostTagId")
                        .HasName("PK__PostTags__325724FD06B3B301");

                    b.HasIndex("HashtagId");

                    b.HasIndex("PostId");

                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Posts", b =>
                {
                    b.Property<long>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<byte>("Privacy")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PostId")
                        .HasName("PK__Posts__AA1260181FCF6913");

                    b.HasIndex("UserId", "CreatedOn");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.RateLimits", b =>
                {
                    b.Property<int>("RateLimitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WindowEnd")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("WindowStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("RateLimitId")
                        .HasName("PK__RateLimi__0B581845C15C954D");

                    b.HasIndex("UserId");

                    b.ToTable("RateLimits");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Reactions", b =>
                {
                    b.Property<long>("ReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReactionId")
                        .HasName("PK__Reaction__46DDF9B4933872DA");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId", "CommentId")
                        .IsUnique()
                        .HasName("UX_Reaction_User_Target")
                        .HasFilter("[PostId] IS NOT NULL AND [CommentId] IS NOT NULL");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.SearchIndex", b =>
                {
                    b.Property<int>("SearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("SearchId")
                        .HasName("PK__SearchIn__21C535F484ACCA41");

                    b.ToTable("SearchIndex");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Stories", b =>
                {
                    b.Property<long>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StoryId")
                        .HasName("PK__Stories__3E82C048965EC5E3");

                    b.HasIndex("UserId", "ExpiresOn");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.TblAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("GoogleMapLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("PinCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AddressId")
                        .HasName("PK__TblAddre__091C2AFBB2FE51AF");

                    b.HasIndex("UserId");

                    b.ToTable("TblAddress");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.TblSocial", b =>
                {
                    b.Property<int>("SocialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FacebookProfile")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Flickr")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Github")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Google")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Skype")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SocialId")
                        .HasName("PK__TblSocia__67CF711A78A170B5");

                    b.HasIndex("UserId");

                    b.ToTable("TblSocial");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.TblUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("LastActiveOn")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("TownCity")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("UQ__TblUser__A9D10534C2F22E84");

                    b.HasIndex("LastActiveOn");

                    b.ToTable("TblUser");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.TblUserPaymentCard", b =>
                {
                    b.Property<int>("PaymentCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ExpiryMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpiryYear")
                        .HasColumnType("int");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentCardId")
                        .HasName("PK__TblUserP__833403D82358948C");

                    b.HasIndex("UserId");

                    b.ToTable("TblUserPaymentCard");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.TbleUserPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("NewPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("OldPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tble_UserPassword");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.UserFeed", b =>
                {
                    b.Property<long>("FeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FeedId")
                        .HasName("PK__UserFeed__1586DF5566872EAB");

                    b.HasIndex("UserId", "CreatedOn");

                    b.ToTable("UserFeed");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.UserMentions", b =>
                {
                    b.Property<int>("MentionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("MentionedUserId")
                        .HasColumnType("int");

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint");

                    b.HasKey("MentionId")
                        .HasName("PK__UserMent__5D9162DCFDD9DD8D");

                    b.HasIndex("CommentId");

                    b.HasIndex("MentionedUserId");

                    b.HasIndex("PostId");

                    b.ToTable("UserMentions");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Comments", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.Posts", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_Comment_Post")
                        .IsRequired();

                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Comment_User")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.ContentReports", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "Reporter")
                        .WithMany("ContentReports")
                        .HasForeignKey("ReporterId")
                        .HasConstraintName("FK_Report_Reporter")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.ConversationMembers", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.Conversations", "Conversation")
                        .WithMany("ConversationMembers")
                        .HasForeignKey("ConversationId")
                        .HasConstraintName("FK_CM_Conversation")
                        .IsRequired();

                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "User")
                        .WithMany("ConversationMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_CM_User")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Friendships", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "Addressee")
                        .WithMany("FriendshipsAddressee")
                        .HasForeignKey("AddresseeId")
                        .HasConstraintName("FK_Friend_Addressee")
                        .IsRequired();

                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "Requester")
                        .WithMany("FriendshipsRequester")
                        .HasForeignKey("RequesterId")
                        .HasConstraintName("FK_Friend_Requester")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.GroupMembers", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.Groups", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK_GM_Group")
                        .IsRequired();

                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "User")
                        .WithMany("GroupMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_GM_User")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Groups", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "CreatedByNavigation")
                        .WithMany("Groups")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Group_Creator")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.MediaFiles", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "OwnerUser")
                        .WithMany("MediaFiles")
                        .HasForeignKey("OwnerUserId")
                        .HasConstraintName("FK_Media_Owner");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.MessageAttachments", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.Messages", "Message")
                        .WithMany("MessageAttachments")
                        .HasForeignKey("MessageId")
                        .HasConstraintName("FK_MA_Message")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.MessageReceipts", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.Messages", "Message")
                        .WithMany("MessageReceipts")
                        .HasForeignKey("MessageId")
                        .HasConstraintName("FK_Receipt_Message")
                        .IsRequired();

                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "User")
                        .WithMany("MessageReceipts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Receipt_User")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Messages", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.Conversations", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .HasConstraintName("FK_Message_Conversation")
                        .IsRequired();

                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Message_Sender")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Notifications", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "Actor")
                        .WithMany("NotificationsActor")
                        .HasForeignKey("ActorId")
                        .HasConstraintName("FK_Notification_Actor");

                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "User")
                        .WithMany("NotificationsUser")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Notification_User")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.PostMedia", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.Posts", "Post")
                        .WithMany("PostMedia")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_PostMedia_Post")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.PostTags", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.Hashtags", "Hashtag")
                        .WithMany("PostTags")
                        .HasForeignKey("HashtagId")
                        .HasConstraintName("FK__PostTags__Hashta__42E1EEFE");

                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.Posts", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK__PostTags__PostId__41EDCAC5");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Posts", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Post_User")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.RateLimits", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "User")
                        .WithMany("RateLimits")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__RateLimit__UserI__30C33EC3");
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Reactions", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.Comments", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .HasConstraintName("FK_Reaction_Comment");

                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.Posts", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_Reaction_Post");

                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Reaction_User")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.Stories", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "User")
                        .WithMany("Stories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Story_User")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.TblAddress", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "User")
                        .WithMany("TblAddress")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__TblAddres__UserI__3C69FB99")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.TblSocial", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "User")
                        .WithMany("TblSocial")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__TblSocial__UserI__4222D4EF")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.TblUserPaymentCard", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "User")
                        .WithMany("TblUserPaymentCard")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__TblUserPa__UserI__47DBAE45")
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.TbleUserPassword", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "User")
                        .WithMany("TbleUserPassword")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Tble_UserPassword_Users")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMithila.SharedDataAccess.EFCore.UserMentions", b =>
                {
                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.Comments", "Comment")
                        .WithMany("UserMentions")
                        .HasForeignKey("CommentId")
                        .HasConstraintName("FK__UserMenti__Comme__3D2915A8");

                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.TblUser", "MentionedUser")
                        .WithMany("UserMentions")
                        .HasForeignKey("MentionedUserId")
                        .HasConstraintName("FK__UserMenti__Menti__3E1D39E1");

                    b.HasOne("SocialMithila.SharedDataAccess.EFCore.Posts", "Post")
                        .WithMany("UserMentions")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK__UserMenti__PostI__3C34F16F");
                });
#pragma warning restore 612, 618
        }
    }
}
